feat: Firebase setup - Added Android native method for requesting permissions and fetching device tokens.
candlefinance/push pull request #3
Opened 2024-02-15 19:32 UTC by vijaygojiya

2024-02-15 23:24 UTC, gtokman requested changes
Nice! thanks for this, few comments.

Last part is the listeners: https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript

2024-02-15 23:24 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/PushModule.kt
> +  fun getToken(promise: Promise) {
#req to match iOS 
```suggestion
  fun registerForToken(promise: Promise) {
```

2024-02-15 23:24 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/PushModule.kt
> +            }
```suggestion
            val listener = PermissionListener { requestCode: Int, _: Array<String>, grantResults: IntArray ->
    if (requestCode == currentRequestCode) {
        val isPermissionGranted = grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED
        promise.resolve(isPermissionGranted)
        return@PermissionListener true
    }
    return@PermissionListener false
}
```

2024-02-15 23:24 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/PushModule.kt
> +            }
#nth a bit more concise

2024-02-15 23:24 UTC, gtokman commented on example/src/App.tsx
> +              console.log('Error while fetching deivce FCM token', e);
#req can remove this and use the button above

2024-02-15 23:24 UTC, gtokman commented on src/index.tsx
> +    // return false;
#req delete these

2024-02-15 23:24 UTC, gtokman commented on src/index.tsx
> +
#req lets use the function `registerForToken` and remove this

2024-02-16 23:13 UTC, gtokman approved these changes
Nice 🚀

2024-02-17 00:20 UTC, gtokman commented
#1 adds the first part; now, all that is left is the emitter part (https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript)

@vijaygojiya Let me know if you want to tackle that. I'm imagining something like this:
```kotlin
class PushPackage : ReactPackage {
  
  data class Action (val type: String, val payload: Map<String, Any?>)

  private var isInitialized = false
  private val queue = mutableListOf<Action>()
  private var module: PushModule? = null

  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
    module = PushModule(reactContext)

    module?.onInitialized = {
      isInitialized = true
      queue.forEach {
        module?.dispatch(it.type, it.payload)
      }
      queue.clear()
    }
    
    return listOf(module as NativeModule)

  }

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return emptyList()
  }

  fun dispatch(action: String, payload: Map<String, Any?>) {
    if (isInitialized) {
      module?.dispatch(action, payload)
    } else {
      queue.add(Action(action, payload))
    }
  }
}
```
// in PushModule

```
 // Example method
  // See https://reactnative.dev/docs/native-modules-android
  @ReactMethod
  fun addListener(eventName: String?) {
    // Keep: Required for RN built in Event Emitter Calls.
  }

  @ReactMethod
  fun removeListeners(count: Int?) {
    // Keep: Required for RN built in Event Emitter Calls.
  }

  fun dispatch(action: String, payload: Map<String, Any?>) {
    val map = mapOf(
        "type" to action,
        "payload" to payload
      )
      val event: WritableMap = Arguments.makeNativeMap(map)
      reactApplicationContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
        .emit(ON_STORE_ACTION, event)
  }
  ```

2024-02-17 03:23 UTC, vijaygojiya commented
> #1 adds the first part; now, all that is left is the emitter part (https://reactnative.dev/docs/native-modules-android#sending-events-to-javascript)
> 
> @vijaygojiya Let me know if you want to tackle that. I'm imagining something like this:
> ```kotlin
> class PushPackage : ReactPackage {
>   
>   data class Action (val type: String, val payload: Map<String, Any?>)
> 
>   private var isInitialized = false
>   private val queue = mutableListOf<Action>()
>   private var module: PushModule? = null
> 
>   override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
>     module = PushModule(reactContext)
> 
>     module?.onInitialized = {
>       isInitialized = true
>       queue.forEach {
>         module?.dispatch(it.type, it.payload)
>       }
>       queue.clear()
>     }
>     
>     return listOf(module as NativeModule)
> 
>   }
> 
>   override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
>     return emptyList()
>   }
> 
>   fun dispatch(action: String, payload: Map<String, Any?>) {
>     if (isInitialized) {
>       module?.dispatch(action, payload)
>     } else {
>       queue.add(Action(action, payload))
>     }
>   }
> }
> ```
> // in PushModule
> 
> ```kotlin
>  companion object {
>     const val notificationReceived = "notificationReceived"
>     const val deviceTokenReceived = "deviceTokenReceived"
>     const val errorReceived = "errorReceived"
>   }
> 
>   override fun getConstants() = mapOf(
>          ...
>   )
>   
>  // Example method
>   // See https://reactnative.dev/docs/native-modules-android
>   @ReactMethod
>   fun addListener(eventName: String?) {
>     // Keep: Required for RN built in Event Emitter Calls.
>   }
> 
>   @ReactMethod
>   fun removeListeners(count: Int?) {
>     // Keep: Required for RN built in Event Emitter Calls.
>   }
> 
>   fun dispatch(action: String, payload: Map<String, Any?>) {
>     val map = mapOf(
>         "type" to action,
>         "payload" to payload
>       )
>       val event: WritableMap = Arguments.makeNativeMap(map)
>       reactApplicationContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
>         .emit("...", event)
>   }
>   ```
> 
> 
> 

Yes, I will take care of this today. Thanks

2024-02-17 20:14 UTC, vijaygojiya commented
@gtokman Could you please review my implementation for the events emitter?. also need help on understanding event queue and dispatching event actions.

2024-02-18 01:10 UTC, gtokman requested changes

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/MyFirebaseMessagingService.kt
> +  // fun onSendError(messageId: String?, sendError: Exception?) {
#req I'd loose the `My` prefix

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/MyFirebaseMessagingService.kt
> +  // }
#req remove this

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/NotificationUtils.kt
> +  private val NOTIFICATION_ID = 123321
#? do we need to inject these from the JS side? If so, we might need to add an init function. I have ideas but never done Android push.

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/NotificationUtils.kt
> +  fun sendNotification(context: Context, title: String, message: String) {
#req add new line

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/NotificationUtils.kt
> +      .setContentText(message)
#? do we need to inject this, too? Is this like the app icon shown in the push?

2024-02-18 01:10 UTC, gtokman commented on src/index.tsx
>    public removeListener<T extends keyof NotificationCallbacks>(event: T): void {
#req remove ios check

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/MyFirebaseMessagingService.kt
> +    RNEventEmitter.sendEvent("deviceTokenReceived",title)
#? can you add a companion object

```
 companion object {
    const val notificationReceived = "notificationReceived"
    const val deviceTokenReceived = "deviceTokenReceived"
    const val errorReceived = "errorReceived"
  }
  
```

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/PushModule.kt
>    companion object {
#req new line

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/RNEventEmitter.java
> +      }
#nth log error

2024-02-18 01:10 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/PushModule.kt
> +    FirebaseMessaging.getInstance().token.addOnCompleteListener(OnCompleteListener { task ->
#req can you add the last method and remove the ios check in the index.ts

```
  @ReactMethod
  fun isRegisteredForRemoteNotifications(promise: Promise) {
    val token = FirebaseMessaging.getInstance().token
    promise.resolve(token != null)
  }
  ```

2024-02-18 01:15 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/RNEventEmitter.java
> +
#? can we make this Kotlin

2024-02-18 01:15 UTC, gtokman commented on android/src/main/java/com/candlefinance/push/ContextHolder.java
> +public class ContextHolder {
#req make this Kotlin

2024-02-18 01:15 UTC, gtokman commented
> @gtokman Could you please review my implementation for the events emitter?. also need help on understanding event queue and dispatching event actions.

We probably don't need the queue, but you are good with the RNEmitter singleton you made regarding the dispatching events. After responding to my feedback, I will prob have to make a demo app on Firebase and see if this works.

2024-02-18 18:26 UTC, vijaygojiya commented on android/src/main/java/com/candlefinance/push/NotificationUtils.kt
> +  private val NOTIFICATION_ID = 123321
- Will do more R& D on it and improve.

2024-02-19 16:46 UTC, vijaygojiya commented on android/src/main/java/com/candlefinance/push/NotificationUtils.kt
> +      .setContentText(message)
Essentially, we now require an icon when sending notifications, and I've also introduced a feature to easily change this icon. Developers can customize the notification icon by adding a new asset to the 'drawable' folder with the exact name ```ic_default_notification```.

2024-02-23 01:26 UTC, merged